spring.application.name=DevDiary

spring.datasource.url=jdbc:mysql://localhost:3306/devdiary
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash

